name: CI

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:
  ci:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        rust: [ stable ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        id: install-rust
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.rust }}
      - name: Test
        run: cargo test --all --all-features
      - name: Clippy
        run: cargo clippy --all --all-features -- -D warnings
